lib/arborist/build-ideal-tree.js, lib/arborist/reify.js, lib/proc-log.js, lib/tracker.js, test/tracker.js
This is PR adds:
- new `Tracker` class that expects a `npmlog` object, otherwise it will default to a fallback logger
- tracker blocks for dependency progress in `Arborist.buildIdealTree` 
- tracker blocks for reify nodes in `Arborist.reify`
- 100% test coverage for `Tracker` class
=> Logging and progress bar for Arborist

README.md, lib/add-rm-pkg-deps.js, lib/arborist/build-ideal-tree.js, lib/arborist/reify.js, lib/update-dep-spec.js, package-lock.json, package.json, tap-snapshots/test-arborist-build-ideal-tree.js-TAP.test.js, tap-snapshots/test-arborist-reify.js-TAP.test.js, test/add-rm-pkg-deps.js, test/arborist/build-ideal-tree.js, test/arborist/reify.js, test/update-dep-spec.js
The previous revision of the buildIdealTree/reify `add` option converted
the package.json-esque data structure into instead passing a list of
specs for each location in the package, since the name couldn't be known
100% of the time up front.
However, that still puts too much of the burden of placing deps onto the
caller.
When you run `npm install foo`, if `foo` is already a devDependency,
then the updated save spec gets added there, unless specified otherwise.
Since we aren't guaranteed to know the _name_ of the dep until we've
resolved it, how is the caller (ie, the npm CLI) supposed to know where
to put it in the objecet?
At the expense of a slight amount of flexibility, this changes things
further so that the `add` option mirrors exactly the positional
arguments passed to the `npm …
=> further simplify adding new deps to the root

lib/arborist/build-ideal-tree.js, lib/arborist/index.js, lib/arborist/load-actual.js, lib/arborist/reify.js, lib/calc-dep-flags.js, lib/shrinkwrap.js, scripts/reify.js, tap-snapshots/test-arborist-reify.js-TAP.test.js, test/arborist/reify.js
Emit a 'time' event for various things, and then a timeEnd event when that
thing is completed.  This is picked up by the CLI in its logger when the
loglevel is set to 'timing', but can also be consumed by any module using
arborist in a generic way.
Close #55
=> track timing via process time/timeEnd events

lib/node.js, scripts/actual.js, scripts/funding.js, scripts/virtual.js, test/node.js
Right now if your cwd is `/` `npm exec`, `npm ls` (or any arborist-dependent
command) will fail with a "could not detect node name from path or
package" error.
This patches add a manual `"system-root"` name to allow arborist to build
a tree from `/`
=> fix: support system root path with no pkg name

lib/arborist/build-ideal-tree.js, test/arborist/build-ideal-tree.js
=> Reset flags when initializing ideal from actual

lib/arborist/reify.js, tap-snapshots/test-arborist-reify.js-TAP.test.js, test/arborist/reify.js
npm6 used to mkdir paths along the way if `--prefix` folder was missing, this seems like an unintentional change so this change fixes it by adding a proper path validation/mkdirp at the beggining of reify.
Fixes: https://github.com/npm/cli/issues/2012
=> fix: should create prefix path if missing

lib/arborist/reify.js
this is maybe not the ideal approach, but it resolves the issue identified [here](https://github.com/npm/cli/issues/2277)
fixes https://github.com/npm/cli/issues/2277
=> remove global guard on validatePath

.gitignore, lib/arborist/build-ideal-tree.js, lib/arborist/reify.js, lib/printable.js, test/arborist/build-ideal-tree.js, test/fixtures/index.js
this is an effort to make the ideal tree more closely resemble reality, when we know the root is a Link we should build our ideal tree also rooted on a Link so that the diffing algorithm works as expected.
as a bonus, this also removes the build-ideal-tree test specific printable tree in favor of using the now built-in toJSON method on the trees.
=> behave properly when root is a symlink in build-ideal-tree

lib/arborist/reify.js, lib/signal-handling.js, lib/signals.js, tap-snapshots/test-signals.js-TAP.test.js, test/arborist/reify.js, test/signal-handling.js, test/signals.js
Rollback when a fatal signal arrives during reification
This also fixes an issue where the rollback did not properly restore the
state if installing a _new_ package, since there was no move required
when creating the sparse tree in that case, resulting in potentially
half-installed deps being left behind.  Found while combing through
testing every rollback for signal handling.
Fix: https://github.com/npm/cli/issues/2312
=> Rollback when a fatal signal arrives during reification

lib/arborist/build-ideal-tree.js, test/arborist/build-ideal-tree.js, test/fixtures/registry-mocks/content/isaacs/test-conflicted-optional-peer-dep-has-peer-optional.json, test/fixtures/registry-mocks/content/isaacs/test-conflicted-optional-peer-dep-has-peer-optional.min.json, test/fixtures/registry-mocks/content/isaacs/test-conflicted-optional-peer-dep-has-peer.json, test/fixtures/registry-mocks/content/isaacs/test-conflicted-optional-peer-dep-has-peer.min.json, test/fixtures/registry-mocks/content/isaacs/test-conflicted-optional-peer-dep-meta-peer-optional.json, test/fixtures/registry-mocks/content/isaacs/test-conflicted-optional-peer-dep-meta-peer-optional.min.json, test/fixtures/registry-mocks/content/isaacs/test-conflicted-optional-peer-dep-meta-peer.json, test/fixtures/registry-mocks/content/isaacs/test-conflicted-optional-peer-dep-meta-peer.min.json, test/fixtures/registry-mocks/content/isaacs/test-conflicted-optional-peer-dep-peer.json, test/fixtures/registry-mocks/content/isaacs/test-conflicted-optional-peer-dep-peer.min.json, test/fixtures/test-conflicted-optional-peer-dep/has-peer-optional/package.json, test/fixtures/test-conflicted-optional-peer-dep/has-peer/package.json, test/fixtures/test-conflicted-optional-peer-dep/meta-peer-optional/package.json, test/fixtures/test-conflicted-optional-peer-dep/meta-peer/package.json, test/fixtures/test-conflicted-optional-peer-dep/nest-peer-optional/package.json, test/fixtures/test-conflicted-optional-peer-dep/omit-peer-optional/package.json, test/fixtures/test-conflicted-optional-peer-dep/peer/1/package.json, test/fixtures/test-conflicted-optional-peer-dep/peer/2/package.json
Detect conflicts among nested peerOptional deps
We do not normally install optional peerDependencies, so we were
skipping over them when building up the peer set that is evaluated for
placement within the tree.
However, if an optional peer dep _conflicts_ with something in the tree,
then it will be seen as an invalid edge, and attempt resolution.
This results in a problem in the following scenario:
```
root -> (a, x)
a -> b
b -> PEER(k@1)
x -> y
y -> PEEROPTIONAL(k@2)
```
We place a, b, k@1, and x in the root node_modules without incident.
Then, we evaluate y, and did not add `k@2` to its peerSet, because it
is a peerOptional.  Since it does not have any apparent peers to
conflict, it is _also_ placed at the root level.
Then, we look to the invalid edges coming out of `y`, and find `k@2` …
=> Detect conflicts among nested peerOptional deps

lib/arborist/build-ideal-tree.js, test/arborist/build-ideal-tree.js, test/fixtures/registry-mocks/content/isaacs/test-peer-looser-than-dev-a-peer-dep.json, test/fixtures/registry-mocks/content/isaacs/test-peer-looser-than-dev-a-peer-dep.min.json, test/fixtures/registry-mocks/content/isaacs/test-peer-looser-than-dev-devdep.json, test/fixtures/registry-mocks/content/isaacs/test-peer-looser-than-dev-devdep.min.json, test/fixtures/test-peer-looser-than-dev/a-peer-dep/1/package.json, test/fixtures/test-peer-looser-than-dev/a-peer-dep/2/package.json, test/fixtures/test-peer-looser-than-dev/devdep/package.json, test/fixtures/test-peer-looser-than-dev/package.json
Given the following dep graph:
```
root -> a@*, b@2
b -> PEER(a@1)
```
when we load the peerSet for `b@2`, we pull in the parent's
spec for that dependency, `a@*`.  This may result in adding `a@2` to the
tree, which conflicts with b's peer dependency.  However, `a@1` would
have _also_ satisfied the root's dependency and _not_ caused a conflict.
When there is no version that can be found to satisfy both dependencies,
then we use the parent's dependency and warn/crash as we would have
previously.  However, with this commit, we are more aggressively
deduplicating the parent/child dependency collision to avoid ERESOLVEs
that are unnecessary.
This increased deduplication results in a lot of churn in the test
snapshot, because it typically means getting an earlier or more
restrictive version of …
=> Prevent ERESOLVEs caused by loose root dep specs

lib/arborist/reify.js, lib/update-root-package-json.js, test/update-root-package-json.js
Reify currently duplicates entries listed as optionalDependencies in the
users' package.json files. While it's working as expected this is
unexpected to a number of users and it also contradicts our own docs on
it:
Entries in optionalDependencies will override entries of the same
name in dependencies, so it's usually best to only put in one place.
This patches this UX problem by adding an extra check that will avoid
adding a dependency to the package.json `dependencies` object in case
that package is already listed under `optionalDependencies`.
Fixes: https://github.com/npm/cli/issues/2203
Fixes: https://github.com/npm/cli/issues/1886
Fixes: https://github.com/npm/cli/issues/724
EDIT(isaacs): Moved this into updateRootPackageJson in pairing session
Alternative approach for …
=> fix: package.json saving optional deps

lib/calc-dep-flags.js, tap-snapshots/test-arborist-load-actual.js-TAP.test.js, tap-snapshots/test-shrinkwrap.js-TAP.test.js, test/arborist/build-ideal-tree.js, test/fixtures/link-dep-has-dep-with-optional-dep/a/package.json, test/fixtures/link-dep-has-dep-with-optional-dep/package.json
When having optional dependencies of a dependency of
a top-level link dependency, e.g:
root -> LINK(a)
a -> (b)
b -> OPTIONAL(c)
* c marked as extraneous
Any optional dependency (and all its nested nodes) were marked
as extraneous in package-lock due to `calcDepFlags` missing
properly following the target of Link nodes.
This changeset fixes it by properly following the result of the
`treeverse.visit` method that will have already followed any
link targets at that point.
Fixes: https://github.com/npm/cli/issues/2505
=> fix: deps of linked deps in package-lock

lib/edge.js, test/edge.js
when analyzing a dep graph its useful to see if an Edge is a `bundledDependencies` edge. this is especially useful when trying to understand the provenance of a package's content.
This PR adds a `bundled` getter property to the `Edge.prototype` which returns true if its a `bundledDependencies` edge or not.
Related to https://github.com/npm/cli/pull/2750
=> Feature: Edges have a "bundled" getter for when they represents a bundled dependency

lib/arborist/build-ideal-tree.js, lib/printable.js, lib/shrinkwrap.js, tap-snapshots/test-arborist-load-actual.js-TAP.test.js, tap-snapshots/test-arborist-load-virtual.js-TAP.test.js, tap-snapshots/test-arborist-reify.js-TAP.test.js, tap-snapshots/test-calc-dep-flags.js-TAP.test.js, tap-snapshots/test-printable.js-TAP.test.js, test/arborist/build-ideal-tree.js, test/fixtures/registry-mocks/content/isaacs/testing-peer-dep-conflict-chain-vv.json, test/fixtures/registry-mocks/content/isaacs/testing-peer-dep-conflict-chain-vv.min.json, test/fixtures/testing-peer-dep-conflict-chain/vv/1/package.json, test/fixtures/testing-peer-dep-conflict-chain/vv/2/package.json, test/printable.js, test/shrinkwrap.js
Previously, we were not including link targets in the virtual trees
where peer dependency sets are calculated.  Additionally, we were still
using the path `/virtual-root` for the virtual node, even though this is
no longer load-bearing.  (And, as of the other change in this PR to the Node
printable output, no longer necessary or particularly helpful for
debugging.)
As a result, a link dependency from the root node like `file:../../foo`
would get resolved against `/virtual-root`, resulting in `/foo`, which
of course does not match any Node in the virtual tree.  The outcome was
an ERESOLVE error where the `current` Node is shown as having no name
or version (because it is an unsatisfied Link).
The solution is two-part.
First, the path of the virtual tree root now matches the path of the …
=> Respect link deps when calculating peerDep sets

lib/add-rm-pkg-deps.js, test/add-rm-pkg-deps.js
There's a bit of logic in npm/cli that sets the `saveBundle` option to
false based on the various `--save-xyz` flags.  It is easier and safer
to just never bundle if we're saving a peer dep, in the one place where
that decision is made.
=> Never bundle when saving as peer/peerOptional

bin/lib/logging.js, bin/lib/timers.js, lib/arborist/rebuild.js, lib/arborist/reify.js, lib/debug.js, tap-snapshots/test/arborist/reify.js.test.cjs, test/arborist/reify.js, test/debug.js
If a package had a dependency on `file:.` (ie, to create a symbolic link
to the root project within `node_modules`), as well as a
`bundleDependencies` list, the reifier got into a very strange state and
would fail to resolve its promise, causing npm to exit with a `cb()
never called` error.
The solution is:
- Do not do the extract-and-loadActual pass on dependencies that are
links.
- Do not create sparse tree folders for dependencies that are links.
(This wasn't a part of the issue, just a weird inefficiency
encountered along the way.  We created a dir, only to delete it and
replace with a symlink later.)
- Later on in the process, when we check to see whether a node has
already been reified by virtue of having bundleDependencies, instead
of merely looking at the package.json data, …
=> Properly handle file:. dep when bundle deps present

bin/license.js, lib/add-rm-pkg-deps.js, lib/arborist/build-ideal-tree.js, lib/arborist/load-virtual.js, lib/arborist/rebuild.js, lib/audit-report.js, lib/printable.js, lib/shrinkwrap.js, lib/update-root-package-json.js, lib/vuln.js, lib/yarn-lock.js, package-lock.json, package.json, test/arborist/rebuild.js, test/arborist/reify.js, test/audit-report.js, test/diff.js, test/fixtures/index.js, test/gather-dep-set.js, test/inventory.js
Node will use the current environment's locale sorting for
String.localeCompare.  Thankfully, String.localeCompare can take a
second argument to specify the locale.  Up until Node 13, any valid
argument provided to the function _may_ be respected if Node was
compiled with Intl support, or would always be treated as `'en'`
otherwise.
The solution is to always set the locale to `'en'`.  An alternative
solution would be to compare strings based on byte order, but this does
not provide ideal ergonomis.
To verify this, the locale is set in the test environment to `'sk'`,
which has a significantly different alphabet, including sorting words
starting with `'ch'` _after_ words starting with `'d'`.
Re: npm/cli#2829
Fix: #276
=> guard against locale-specific sorting

lib/node.js, test/node.js
Added to the result object of node.explain():
- `isWorkspace`, boolean value, true when a node is a workspace
- `linksIn`, array containing all links to a target
This is going to be useful in the **cli** in order to identify a workspace node at the end of the dependency chain.
=> add extra info to node.explain

lib/arborist/audit.js, lib/arborist/build-ideal-tree.js, lib/arborist/index.js, lib/arborist/rebuild.js, lib/arborist/reify.js, tap-snapshots/test/arborist/load-virtual.js.test.cjs, tap-snapshots/test/arborist/reify.js.test.cjs, test/arborist/audit.js, test/arborist/build-ideal-tree.js, test/arborist/index.js, test/arborist/reify.js, test/fixtures/workspaces-shared-deps-virtual/package-lock.json, test/fixtures/workspaces-shared-deps-virtual/package.json
Added the ability to include workspace root or to filter out workspaces entirely `--enableWorkspaces` `--includeWorkspaceRoot` for arborist commands.
When `enableWorkspaces` is false, commands that would normally dive into workspaces do not.
When workspaces are specified, using `includeWorkspaceRoot` includes the root package in the context of those commands.
=> workspaceEnabled and includeWorkspaceRoot config options to extend workspace filters

lib/place-dep.js, test/arborist/build-ideal-tree.js, test/fixtures/registry-mocks/content/lukekarrys/workspace-peer-dep-infinite-loop-a.json, test/fixtures/registry-mocks/content/lukekarrys/workspace-peer-dep-infinite-loop-a.min.json, test/fixtures/registry-mocks/content/lukekarrys/workspace-peer-dep-infinite-loop-b.json, test/fixtures/registry-mocks/content/lukekarrys/workspace-peer-dep-infinite-loop-b.min.json, test/fixtures/registry-mocks/content/lukekarrys/workspace-peer-dep-infinite-loop-c.json, test/fixtures/registry-mocks/content/lukekarrys/workspace-peer-dep-infinite-loop-c.min.json, test/fixtures/registry-mocks/content/lukekarrys/workspace-peer-dep-infinite-loop-d.json, test/fixtures/registry-mocks/content/lukekarrys/workspace-peer-dep-infinite-loop-d.min.json
While fixing npm/cli#3933 I wrote tests to confirm the behavior and noticed that a case with an overlapping peerSet was warning when it shouldn't be.
This tree should be able to be built with `c@1` and `d@1`, which it does, but with a warning. In `2.8.3` it correctly doesn't give an `ERESOLVE` warning, so I think it's a regression in `2.8.4`.
```
// overlapping peerSet
project -> (a@1)
a@1 -> (b), PEER(c@1||2), PEER(d@1||2)
b -> PEER(c@1), PEER(d@1)
c -> ()
d@1 -> PEER(c@1)
d@2 -> PEER(c@2)
```
I also found that a similar tree with a conflicting peerSet was also causing the infinite loop when installed in a workspace. When testing that case I found that building this tree in a root vs a workspace ended up with different versions of `c` and `d`.
```
// conflicting peerSet
project -> (a@2) …
```
=> fix: stop pruning peerSets when entryEdge is from a workspace

lib/arborist/index.js, tap-snapshots/test/arborist/pruner.js.test.cjs, test/arborist/index.js, test/arborist/pruner.js
`arborist.excludeWorkspaceDependencySet` properly handles dependencies that
are both root and workspace deps for commands like prune, npm ls, etc.
Previously, commands like `arborist prune --workspacesEnabled=false` would prune packages erroneously if they were both a workspace and a root dependency.
=> fix: ws no longer filter root deps

lib/arborist/build-ideal-tree.js, lib/arborist/load-actual.js, lib/arborist/load-virtual.js, lib/edge.js, lib/node.js, lib/override-set.js, lib/place-dep.js, lib/printable.js, package-lock.json, package.json, tap-snapshots/test/edge.js.test.cjs, tap-snapshots/test/node.js.test.cjs, tap-snapshots/test/place-dep.js.test.cjs, tap-snapshots/test/printable.js.test.cjs, test/arborist/build-ideal-tree.js, test/edge.js, test/node.js, test/override-set.js, test/place-dep.js, test/printable.js
This pull request implements overrides as described in [the spec](https://github.com/npm/rfcs/blob/main/accepted/0036-overrides.md)
~There are a couple of todo notes for myself in the code that I'm going through my notes to find context on, so this is a draft until I get those sorted out.~ I wasn't able to figure out what the notes were meant to address. Since tests tell a positive story here, I'm leaving the comments as they are in case of future issues and this is ready for review
=> feat: implement overrides
